version: '3.2'

services:
  iface-mon-ot:
    image: ${REGISTRY:-hub.foundries.io}/iface-monitor:${TAG:-latest}
    tmpfs:
      - /run
      - /var/lock
      - /var/log
    volumes:
      - /var/run/dbus:/var/dbus
    command: "--interface wpan0 --ip \"fd11:22::1/64\"" --seconds-delay 1
    network_mode: "host"
    restart: always
    read_only: true
    privileged: true
    tty: true

  ot-wpantund:
    image: ${REGISTRY:-hub.foundries.io}/ot-wpantund:${TAG:-latest}
    tmpfs:
      - /run
      - /var/lock
      - /var/log
    depends_on:
      - iface-mon-ot
    network_mode: "host"
    restart: always
    read_only: true
    privileged: true
